//
// Copyright (c) 2022 Croyfet
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//


#ifndef _INCLUDE_GUARD_CRHEADER_ERROR_H_
#define _INCLUDE_GUARD_CRHEADER_ERROR_H_

#ifdef __cplusplus
#include <cstdint>
#include <cstdbool>
#else
#include <stdint.h>
#include <stdbool.h>
#endif

#ifdef __cplusplus
extern "C"
{
#endif

	enum _tag_CcErrorReason
	{
		_CCERROR_REASON_NULLPTR =                       1,
		_CCERROR_REASON_NOT_NULLPTR =                   2,

		_CCERROR_REASON_HANDLE_INITIALIZED =            11,
		_CCERROR_REASON_HANDLE_NOT_INITIALIZED =        12,
		_CCERROR_REASON_HANDLE_NEW =                    13,
		_CCERROR_REASON_HANDLE_INCOMPATIBLE =           14,
		_CCERROR_REASON_HANDLE_BROKEN =                 15,

		_CCERROR_REASON_TOO_BIG =                       30,
		_CCERROR_REASON_TOO_SMALL =                     31,
		_CCERROR_REASON_ONLY_GT =                       32,
		_CCERROR_REASON_ONLY_LT =                       33,
		_CCERROR_REASON_ONLY_GE =                       34,
		_CCERROR_REASON_ONLY_LE =                       35,
		_CCERROR_REASON_NOT_ZERO =                      36,
		_CCERROR_REASON_ONLY_ZERO =                     37,
		_CCERROR_REASON_RANGE_OUT =                     38,

		_CCERROR_REASON_INVALID_ALLOC_SIZE =            51,

		_CCERROR_REASON_INVALID_FLAG =                  61,
		_CCERROR_REASON_INVALID_MULTI_FLAG =            62,
		_CCERROR_REASON_FLAG_NOT_MATCH =                63,

		_CCERROR_REASON_TEXT_NULL_TERMINALED =          70,
		_CCERROR_REASON_TEXT_NOT_NULLTERMINALED =       71,
		_CCERROR_REASON_TEXT_CONTAIN_NULL_CHAR =        72,
		_CCERROR_REASON_TEXT_CONTAIN_CONTROL_CODE =     73,
		_CCERROR_REASON_TEXT_CONTAIN_BREAK_CHAR =       74,
		_CCERROR_REASON_TEXT_CONTAIN_INVALID_CHAR =     75,
		_CCERROR_REASON_TEXT_CONTAIN_INVALID_BREAK =    76,
		_CCERROR_REASON_TEXT_INVALID_CHARCODE =         77,
		_CCERROR_REASON_TEXT_INVALID_BREAK =            78,
		_CCERROR_REASON_TEXT_INVALID_SYNTAX =           79,

		_CCERROR_REASON_INVALID_TYPE =                  92,
		_CCERROR_REASON_INVALID_HANDLE =                93,

		_CCERROR_REASON_FILE_READ =                     111,
		_CCERROR_REASON_FILE_WRITE =                    112,
		_CCERROR_REASON_FILE_CREATE =                   113,
		_CCERROR_REASON_FILE_DELETE =                   114,
		_CCERROR_REASON_FILE_OPEN =                     115,
		_CCERROR_REASON_FILE_MAP =                      116,
		_CCERROR_REASON_FILE_GET =                      117,
		_CCERROR_REASON_FILE_ACCESS =                   118,
		_CCERROR_REASON_FILE_LOCK =                     119,
		_CCERROR_REASON_FILE_NOT_FOUND =                120,
		_CCERROR_REASON_FILE_ARLEADY_EXIST =            121,

		_CCERROR_REASON_DIRECTORY_CREATE =              131,
		_CCERROR_REASON_DIRECTORY_DELETE =              132,
		_CCERROR_REASON_DIRECTORY_GET =                 133,
		_CCERROR_REASON_DIRECTORY_ACCESS =              134,
		_CCERROR_REASON_DIRECTORY_LOCK =                135,
		_CCERROR_REASON_DIRECTORY_NOT_FOUND =           136,
		_CCERROR_REASON_DIRECTORY_ARLEADY_EXIST =       137,

		_CCERROR_REASON_ALLOC_ERROR =                   200,
		_CCERROR_REASON_SYS_TIME_OUT =                  210,
		_CCERROR_REASON_SYS_MANY_CALL =                 211,

		_CCERROR_REASON_DEPRECATED =                    300,
		_CCERROR_REASON_LEGACY =                        301,

		_CCERROR_REASON_UNIMPREMENTED =                 310,

		_CCERROR_REASON_INCOMPATIBLE_OS =               320,
		_CCERROR_REASON_INCOMPATIBLE_COMPILER =         321,
		_CCERROR_REASON_INCOMPATIBLE_PROCESSOR =        322,

		_CCERROR_REASON_VERSION_TOO_OLD =               330,
		_CCERROR_REASON_VERSION_TOO_NEW =               331,
		_CCERROR_REASON_VERSION_NOT_MATCH =             332,

		_CCERROR_REASON_INVALID =                       1000,
		_CCERROR_REASON_WHY_COME_HERE =                 1001,
		_CCERROR_REASON_UNEXPECTED =                    1002,
	};
	typedef enum _tag_CcErrorReason _CcErrorReason;


	enum _tagCcError
	{
		CCERROR_SUCCESS =                           0x00000000,
		CCERROR_FAILED_NULLPTR =                    0x80000000 | _CCERROR_REASON_NULLPTR,
		CCERROR_FAILED_NOT_NULLPTR =                0x80000000 | _CCERROR_REASON_NOT_NULLPTR,

		CCERROR_FAILED_HANDLE_INITIALIZED =         0x80000000 | _CCERROR_REASON_HANDLE_INITIALIZED,
		CCERROR_FAILED_HANDLE_NOT_INITIALIZED =     0x80000000 | _CCERROR_REASON_HANDLE_NOT_INITIALIZED,
		CCERROR_FAILED_HANDLE_NEW =                 0x80000000 | _CCERROR_REASON_HANDLE_NEW,
		CCERROR_FAILED_HANDLE_INCOMPATIBLE =        0x80000000 | _CCERROR_REASON_HANDLE_INCOMPATIBLE,
		CCERROR_FAILED_HANDLE_BROKEN =              0x80000000 | _CCERROR_REASON_HANDLE_BROKEN,

		CCERROR_FAILED_TOO_BIG =                    0x80000000 | _CCERROR_REASON_TOO_BIG,
		CCERROR_FAILED_TOO_SMALL =                  0x80000000 | _CCERROR_REASON_TOO_SMALL,
		CCERROR_FAILED_ONLY_GT =                    0x80000000 | _CCERROR_REASON_ONLY_GT,
		CCERROR_FAILED_ONLY_LT =                    0x80000000 | _CCERROR_REASON_ONLY_LT,
		CCERROR_FAILED_ONLY_GE =                    0x80000000 | _CCERROR_REASON_ONLY_GE,
		CCERROR_FAILED_ONLY_LE =                    0x80000000 | _CCERROR_REASON_ONLY_LE,
		CCERROR_FAILED_NOT_ZERO =                   0x80000000 | _CCERROR_REASON_NOT_ZERO,
		CCERROR_FAILED_ONLY_ZERO =                  0x80000000 | _CCERROR_REASON_ONLY_ZERO,
		CCERROR_FAILED_RANGE_OUT =                  0x80000000 | _CCERROR_REASON_RANGE_OUT,

		CCERROR_FAILED_INVALID_ALLOC_SIZE =         0x80000000 | _CCERROR_REASON_INVALID_ALLOC_SIZE,

		CCERROR_FAILED_INVALID_FLAG =               0x80000000 | _CCERROR_REASON_INVALID_FLAG,
		CCERROR_FAILED_INVALID_MULTI_FLAG =         0x80000000 | _CCERROR_REASON_INVALID_MULTI_FLAG,
		CCERROR_FAILED_FLAG_NOT_MATCH =             0x80000000 | _CCERROR_REASON_FLAG_NOT_MATCH,

		CCERROR_FAILED_TEXT_NULL_TERMINALED =       0x80000000 | _CCERROR_REASON_TEXT_NULL_TERMINALED,
		CCERROR_FAILED_TEXT_NOT_NULLTERMINALED =    0x80000000 | _CCERROR_REASON_TEXT_NOT_NULLTERMINALED,
		CCERROR_FAILED_TEXT_CONTAIN_NULL_CHAR =     0x80000000 | _CCERROR_REASON_TEXT_CONTAIN_NULL_CHAR,
		CCERROR_FAILED_TEXT_CONTAIN_CONTROL_CODE =  0x80000000 | _CCERROR_REASON_TEXT_CONTAIN_CONTROL_CODE,
		CCERROR_FAILED_TEXT_CONTAIN_BREAK_CHAR =    0x80000000 | _CCERROR_REASON_TEXT_CONTAIN_BREAK_CHAR,
		CCERROR_FAILED_TEXT_CONTAIN_INVALID_CHAR =  0x80000000 | _CCERROR_REASON_TEXT_CONTAIN_INVALID_CHAR,
		CCERROR_FAILED_TEXT_CONTAIN_INVALID_BREAK = 0x80000000 | _CCERROR_REASON_TEXT_CONTAIN_INVALID_BREAK,
		CCERROR_FAILED_TEXT_INVALID_CHARCODE =      0x80000000 | _CCERROR_REASON_TEXT_INVALID_CHARCODE,
		CCERROR_FAILED_TEXT_INVALID_BREAK =         0x80000000 | _CCERROR_REASON_TEXT_INVALID_BREAK,
		CCERROR_FAILED_TEXT_INVALID_SYNTAX =        0x80000000 | _CCERROR_REASON_TEXT_INVALID_SYNTAX,

		CCERROR_FAILED_INVALID_TYPE =               0x80000000 | _CCERROR_REASON_INVALID_TYPE,
		CCERROR_FAILED_INVALID_HANDLE =             0x80000000 | _CCERROR_REASON_INVALID_HANDLE,

		CCERROR_FAILED_FILE_READ =                  0x80000000 | _CCERROR_REASON_FILE_READ,
		CCERROR_FAILED_FILE_WRITE =                 0x80000000 | _CCERROR_REASON_FILE_WRITE,
		CCERROR_FAILED_FILE_CREATE =                0x80000000 | _CCERROR_REASON_FILE_CREATE,
		CCERROR_FAILED_FILE_DELETE =                0x80000000 | _CCERROR_REASON_FILE_DELETE,
		CCERROR_FAILED_FILE_OPEN =                  0x80000000 | _CCERROR_REASON_FILE_OPEN,
		CCERROR_FAILED_FILE_MAP =                   0x80000000 | _CCERROR_REASON_FILE_MAP,
		CCERROR_FAILED_FILE_GET =                   0x80000000 | _CCERROR_REASON_FILE_GET,
		CCERROR_FAILED_FILE_ACCESS =                0x80000000 | _CCERROR_REASON_FILE_ACCESS,
		CCERROR_FAILED_FILE_LOCK =                  0x80000000 | _CCERROR_REASON_FILE_LOCK,
		CCERROR_FAILED_FILE_NOT_FOUND =             0x80000000 | _CCERROR_REASON_FILE_NOT_FOUND,
		CCERROR_FAILED_FILE_ARLEADY_EXIST =         0x80000000 | _CCERROR_REASON_FILE_ARLEADY_EXIST,

		CCERROR_FAILED_DIRECTORY_CREATE =           0x80000000 | _CCERROR_REASON_DIRECTORY_CREATE,
		CCERROR_FAILED_DIRECTORY_DELETE =           0x80000000 | _CCERROR_REASON_DIRECTORY_DELETE,
		CCERROR_FAILED_DIRECTORY_GET =              0x80000000 | _CCERROR_REASON_DIRECTORY_GET,
		CCERROR_FAILED_DIRECTORY_ACCESS =           0x80000000 | _CCERROR_REASON_DIRECTORY_ACCESS,
		CCERROR_FAILED_DIRECTORY_LOCK =             0x80000000 | _CCERROR_REASON_DIRECTORY_LOCK,
		CCERROR_FAILED_DIRECTORY_NOT_FOUND =        0x80000000 | _CCERROR_REASON_DIRECTORY_NOT_FOUND,
		CCERROR_FAILED_DIRECTORY_ARLEADY_EXIST =    0x80000000 | _CCERROR_REASON_DIRECTORY_ARLEADY_EXIST,

		CCERROR_FAILED_ALLOC_ERROR =                0x80000000 | _CCERROR_REASON_ALLOC_ERROR,
		CCERROR_FAILED_SYS_TIME_OUT =               0x80000000 | _CCERROR_REASON_SYS_TIME_OUT,
		CCERROR_FAILED_SYS_MANY_CALL =              0x80000000 | _CCERROR_REASON_SYS_MANY_CALL,

		CCERROR_FAILED_DEPRECATED =                 0x80000000 | _CCERROR_REASON_DEPRECATED,
		CCERROR_FAILED_LEGACY =                     0x80000000 | _CCERROR_REASON_LEGACY,

		CCERROR_FAILED_UNIMPREMENTED =              0x80000000 | _CCERROR_REASON_UNIMPREMENTED,

		CCERROR_FAILED_INCOMPATIBLE_OS =            0x80000000 | _CCERROR_REASON_INCOMPATIBLE_OS,
		CCERROR_FAILED_INCOMPATIBLE_COMPILER =      0x80000000 | _CCERROR_REASON_INCOMPATIBLE_COMPILER,
		CCERROR_FAILED_INCOMPATIBLE_PROCESSOR =     0x80000000 | _CCERROR_REASON_INCOMPATIBLE_PROCESSOR,

		CCERROR_FAILED_VERSION_TOO_OLD =            0x80000000 | _CCERROR_REASON_VERSION_TOO_OLD,
		CCERROR_FAILED_VERSION_TOO_NEW =            0x80000000 | _CCERROR_REASON_VERSION_TOO_NEW,
		CCERROR_FAILED_VERSION_NOT_MATCH =          0x80000000 | _CCERROR_REASON_VERSION_NOT_MATCH,

		CCERROR_FAILED_INVALID =                    0x80000000 | _CCERROR_REASON_INVALID,
		CCERROR_FAILED_WHY_COME_HERE =              0x80000000 | _CCERROR_REASON_WHY_COME_HERE,
		CCERROR_FAILED_UNEXPECTED =                 0x80000000 | _CCERROR_REASON_UNEXPECTED,
	};
	typedef enum _tagCcError CcError;

	inline bool CCERROR_HAS_ERROR(CcError crs) { if ((crs & 0x80000000) == 0x80000000) { return true; } else { return false; } }

	inline bool CCERROR_IS_SUCCESS(CcError crs) { if (crs >= 0x00000000) { return true; } else { return false; } }

#ifdef __cplusplus
}
#endif

#endif
